// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjetoTs.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    [Migration("20240610233300_VersaoInicial")]
    partial class VersaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AvaliacaoFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Altura")
                        .HasColumnType("float");

                    b.Property<float>("CircunferenciaCintura")
                        .HasColumnType("float");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<int>("FrequenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<float>("MassaMuscular")
                        .HasColumnType("float");

                    b.Property<float>("PercentualGordura")
                        .HasColumnType("float");

                    b.Property<float>("Peso")
                        .HasColumnType("float");

                    b.Property<float>("PressaoArterial")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<int>("Carboidratos")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Gorduras")
                        .HasColumnType("int");

                    b.Property<string>("HistoricoDietas")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Proteinas")
                        .HasColumnType("int");

                    b.Property<string>("RestricoesAlimentares")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("Nutricionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Crm")
                        .HasColumnType("longtext");

                    b.Property<string>("Dietas")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Pacientes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Nutricionistas");
                });

            modelBuilder.Entity("Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alunos")
                        .HasColumnType("longtext");

                    b.Property<string>("Cref")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personais");
                });

            modelBuilder.Entity("PersonalTreino", b =>
                {
                    b.Property<int>("PersonaisId")
                        .HasColumnType("int");

                    b.Property<int>("TreinosId")
                        .HasColumnType("int");

                    b.HasKey("PersonaisId", "TreinosId");

                    b.HasIndex("TreinosId");

                    b.ToTable("PersonalTreino");
                });

            modelBuilder.Entity("PlanoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Lanches")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Objetivo")
                        .HasColumnType("longtext");

                    b.Property<string>("Receitas")
                        .HasColumnType("longtext");

                    b.Property<string>("Refeicoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Exercicios")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoTreinos")
                        .HasColumnType("longtext");

                    b.Property<string>("Intensidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoMedico")
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NivelAtividadeFisica")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjetivoSaude")
                        .HasColumnType("longtext");

                    b.Property<float>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Sexo")
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Personal", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Personais")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PersonalTreino", b =>
                {
                    b.HasOne("Personal", null)
                        .WithMany()
                        .HasForeignKey("PersonaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanoAlimentar", b =>
                {
                    b.HasOne("Usuario", null)
                        .WithMany("PlanosAlimentares")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Treino", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Treinos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Personais");

                    b.Navigation("PlanosAlimentares");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
